--- #YAML:1.0
name:                Data-Postponed
version:             0.20
abstract:            Delay the evaluation of expressions to allow post
license:             unknown
generated_by:        ExtUtils::MakeMaker version 6.30_02
author:              "Joshua ben Jore" <jjore@cpan.org>
distribution_type:   module
requires:     
    Scalar::Util:                  0
meta-spec:
    url: <http://module-build.sourceforge.net/META-spec-new.html>;
    version: 1.1
